# model
model_name_or_path: /home/wangguisen/models/Qwen1.5-MoE-A2.7B-Chat
quantization_bit: 4

# method
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj

# ddp
ddp_timeout: 180000000
deepspeed: yamls/ds_z3_config.json

# dataset
dataset: 0_no_dialog_train_data_20240221, 1_dialog_train_data_20240304, 2_dialog_train_data_20240508
template: qwen
cutoff_len: 1024
max_samples: 1000000
val_size: 0.01
overwrite_cache: true
preprocessing_num_workers: 18

# output
output_dir: /home/wangguisen/projects/LLaMA-Factory/weights/
logging_steps: 5
save_steps: 500
plot_loss: true
overwrite_output_dir: true

# train
per_device_train_batch_size: 3
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 0.1
fp16: true
# max_grad_norm: 0.5

# eval
per_device_eval_batch_size: 3
evaluation_strategy: steps
eval_steps: 500
